<?php

use CRM_Contract_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_membership_payment',
    'entity' => 'CustomGroup',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'membership_payment',
        'title' => E::ts('Payment Information'),
        'extends' => 'Membership',
        'style' => 'Inline',
        'weight' => 3,
        'collapse_adv_display' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'extends',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_membership_annual',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'membership_annual',
        'label' => E::ts('Annual Membership Contribution'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'column_name' => 'membership_annual',
        'in_selector' => TRUE,
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_membership_frequency',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'membership_frequency',
        'label' => E::ts('Payment Interval'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'membership_frequency',
        'option_group_id.name' => 'payment_frequency',
        'in_selector' => TRUE,
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_membership_recurring_contribution',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'membership_recurring_contribution',
        'label' => E::ts('Recurring contribution/mandate'),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'membership_recurring_contribution',
        'in_selector' => TRUE,
        'fk_entity' => 'ContributionRecur',
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_to_ba',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'to_ba',
        'label' => E::ts("Organisation's Bank Account"),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'to_ba',
        'in_selector' => TRUE,
        'fk_entity' => 'BankAccount',
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_from_ba',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'from_ba',
        'label' => E::ts("Donor's Bank Account"),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'from_ba',
        'in_selector' => TRUE,
        'fk_entity' => 'BankAccount',
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_cycle_day',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'cycle_day',
        'label' => E::ts('Cycle day'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'cycle_day',
        'in_selector' => TRUE,
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_payment_instrument',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'payment_instrument',
        'label' => E::ts('Payment method'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'payment_instrument',
        'option_group_id.name' => 'payment_instrument',
        'in_selector' => TRUE,
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_membership_payment_CustomField_defer_payment_start',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'membership_payment',
        'name' => 'defer_payment_start',
        'label' => E::ts('Defer Payment Start'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '1',
        'is_searchable' => TRUE,
        'column_name' => 'defer_payment_start',
        'in_selector' => TRUE,
        'is_active' => TRUE,
        'is_view' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
];
