<?php

use CRM_Contract_ExtensionUtil as E;

$activity_type_contract_updated = CRM_Core_PseudoConstant::getKey(
  'CRM_Activity_BAO_Activity',
  'activity_type_id',
  'Contract_Updated'
);

$activity_type_contract_revived = CRM_Core_PseudoConstant::getKey(
  'CRM_Activity_BAO_Activity',
  'activity_type_id',
  'Contract_Revived'
);

return [
  [
    'name' => 'CustomGroup_contract_updates',
    'entity' => 'CustomGroup',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'contract_updates',
        'title' => E::ts('Contract Updates'),
        'extends' => 'Activity',
        'extends_entity_column_value' => [
          $activity_type_contract_updated,
          $activity_type_contract_revived,
        ],
        'style' => 'Inline',
        'weight' => 5,
        'collapse_adv_display' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'name',
        'extends',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_membership_type',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_membership_type',
        'label' => E::ts('Membership Type'),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_membership_type',
        'in_selector' => TRUE,
        'fk_entity' => 'MembershipType',
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_annual',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_annual',
        'label' => E::ts('Annual Membership Contribution'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_annual',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_annual_diff',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_annual_diff',
        'label' => E::ts('Increase'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_annual_diff',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_frequency',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_frequency',
        'label' => E::ts('Payment Interval'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_frequency',
        'option_group_id.name' => 'payment_frequency',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_recurring_contribution',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_recurring_contribution',
        'label' => E::ts('Payment Contract'),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_recurring_contribution',
        'in_selector' => TRUE,
        'fk_entity' => 'ContributionRecur',
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_to_ba',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_to_ba',
        'label' => E::ts('GP Bank Account'),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_to_ba',
        'in_selector' => TRUE,
        'fk_entity' => 'BankAccount',
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_from_ba',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_from_ba',
        'label' => E::ts("Member's Bank Account"),
        'data_type' => 'EntityReference',
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_from_ba',
        'in_selector' => TRUE,
        'fk_entity' => 'BankAccount',
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_cycle_day',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_cycle_day',
        'label' => E::ts('Cycle Day'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_cycle_day',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_payment_instrument',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_payment_instrument',
        'label' => E::ts('Payment Method'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_payment_instrument',
        'option_group_id.name' => 'payment_instrument',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_defer_payment_start',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_defer_payment_start',
        'label' => E::ts('Defer Payment Start'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '1',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'ch_defer_payment_start',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_contract_updates_CustomField_ch_payment_changes',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'contract_updates',
        'name' => 'ch_payment_changes',
        'label' => E::ts('Payment changes'),
        'html_type' => 'Text',
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'text_length' => 1023,
        'column_name' => 'ch_payment_changes',
        'in_selector' => TRUE,
        'is_active' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
];
